Repository astrandb/viva, pull requests merged in 2023-11, with the labels that each got.

#44 Update devcontainer and lint
  .devcontainer.json
  custom_components/viva/sensor.py
Labels: Maintenance

#45 Add Wind Bearing
  custom_components/viva/sensor.py
  custom_components/viva/translations/en.json
  custom_components/viva/translations/sv.json
Labels: enhancement

#46 Add Wave Bearing
  custom_components/viva/sensor.py
  custom_components/viva/translations/en.json
  custom_components/viva/translations/sv.json
Labels: enhancement

#47 Default disable int wave bearing sensor
  custom_components/viva/sensor.py
Labels: enhancement

#48 Return "-" value as None
  custom_components/viva/sensor.py
Labels: bugfix

#49 Add airtemp sensor
  custom_components/viva/sensor.py
Labels: enhancement
